### ISSUE TITLE
make concurrent app start prevention mac friendly

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#139]
there is some developer unfriendliness in the mac dev env, due to the fact that most developers are using Debian or Qubes:

- prevent concurrent app start does not work on mac
- ~~`make test` does not work on mac due to lack of xvfb~~

this is bad because generally at hackathons 90% of attendees use macs for development, so we should resolve

**Comment by heartsucker** [comment]
I know you self assigned this, but I fixed with with a simple `if hash xvfb-run` in a `bash` script as part of another PR. Sorry fren.

**Comment by redshiftzero** [comment]
no worries, thanks for fixing it!

**Comment by redshiftzero** [comment]
this one I'm actually reopening because we still have this concurrent app start prevention issue which  fails on macOS: 

```
$ ./run.sh
Running app with home directory: /var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmp.sZZe3rhC
Traceback (most recent call last):
  File "/Users/redshiftzero/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/redshiftzero/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/__main__.py", line 3, in <module>
    run()
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/app.py", line 187, in run
    start_app(args, qt_args)
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/app.py", line 153, in start_app
    prevent_second_instance(app, args.sdc_home)
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/app.py", line 119, in prevent_second_instance
    app.instance_binding.bind(IDENTIFIER)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by timruffles** [comment]
I'll take a look.
